export const CUSTOMER_DETAILS_FETCH_REQUEST = 'CUSTOMER_DETAILS_FETCH_REQUEST'
export const CUSTOMER_DETAILS_FETCH_SUCCESS = 'CUSTOMER_DETAILS_FETCH_SUCCESS'
export const CUSTOMER_DETAILS_FETCH_FAILURE = 'CUSTOMER_DETAILS_FETCH_FAILURE'
export const CUSTOMER_STOP_ERROR_FALSE = 'CUSTOMER_STOP_ERROR_FALSE'
